#!/bin/sh
git submodule update --init --recursive
pushd ext/appui
sh build
popd
cp ext/appui/lib/* www/ui/scripts/
cp ext/phonegap-plugins/iPhone/Badge/Badge.js www/ui/scripts/
pushd www
python ../ext/appui/external/uimin/uimin.py config.yaml
popd
python run_server.py generate www/index.html
