output_dir: 'www/ui/scripts'
js:
  phonegap_plugins:
    files:
      - 'www/ui/scripts/Badge.js'
      - 'www/ui/scripts/clipboardPlugin.js'
  scribbletasks:
    files:
      - 'www/ui/scripts/iscroll.js'
      - 'www/ui/scripts/debug.js'
      - 'www/ui/scripts/SwipeController.js'
      - 'www/ui/scripts/date-en-US.js'
      - 'www/ui/scripts/ScribbleTasksApp.js'
      - 'www/dataproviders/projects.js'
      - 'www/dataproviders/tasks.js'
      - 'www/models/project.js'
      - 'www/models/task.js'
      - 'www/controllers/add_task.js'
      - 'www/controllers/project.js'
      - 'www/controllers/search.js'
      - 'www/controllers/project_list.js'
      - 'www/controllers/task_menu.js'
      - 'www/controllers/debug_controller.js'
      - 'www/views/scribble.js'
