output_dir: 'ui/scripts'
js:
  phonegap_plugins:
    files:
      - 'ui/scripts/Badge.js'
      - 'ui/scripts/clipboardPlugin.js'
  scribbletasks:
    files:
      - 'ui/scripts/iscroll.js'
      - 'ui/scripts/debug.js'
      - 'ui/scripts/SwipeController.js'
      - 'ui/scripts/date-en-US.js'
      - 'ui/scripts/ScribbleTasksApp.js'
      - 'dataproviders/projects.js'
      - 'dataproviders/tasks.js'
      - 'models/project.js'
      - 'models/task.js'
      - 'controllers/add_task.js'
      - 'controllers/project.js'
      - 'controllers/search.js'
      - 'controllers/project_list.js'
      - 'controllers/task_menu.js'
      - 'controllers/debug_controller.js'
      - 'views/scribble.js'
